name: Build and push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - '**' # Match every branch
    tags:
      - 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: 'robertngo18/sitediff' # ${{ github.repository }}
  RUBY_VERSION: '3.1'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }} # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rspec


  build-deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      -
        name: "Check out"
        uses: actions/checkout@v4

      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      -
        name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: "Extract metadata for Docker"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}

      -
        name: "Test Docker image"
        run: |
          docker run --rm -d ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      -
        name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

